In [7]:
import sys
sys.path.append('D:\Workspace\CryptoBot\venv\Lib\site-packages')

In [77]:
from binance.client import Client
import pandas as pd
import os
main_dir = os.path.dirname(os.getcwd())

'D:\\Workspace\\CryptoBot\\main'

In [71]:
API_KEY = 'KZTDCrbKd94mXzxWOA0LQpx2uDcoXk3okFketEYCLFy6gAyJD4IhITol4JXnZosJ'
API_SECRET = 'kLivDtSd1AOovlgpkNbISQwTBy4vaIWqhJkAkeOkfnFArDNjtGM5sEx9dChhCoO9'
client = Client(API_KEY, API_SECRET)

In [78]:
start = '2021-07-30'
end = None
interval = '1m' 
symbol = 'BTCUSDT'

bars = client.get_historical_klines(symbol , interval , start, end)
df= pd.DataFrame(bars, columns=['Open Time', 'Open', 'High', 'Low', 'Close','Volume','Close Time','QAV','NOT','TBBAV','TBQAV','U'])
df['date'] = pd.to_datetime(df['Close Time']/1000, unit='s')
df = df.drop('Open Time', axis = 1)

,Open,High,Low,Close,Volume,Close Time,QAV,NOT,TBBAV,TBQAV,U,date
0,40018.49000000,40070.00000000,40004.91000000,40019.31000000,47.30457300,1627603259999,1893868.98768562,1620,21.74279900,870459.87070309,0,2021-07-30 00:00:59.999000072
1,40019.31000000,40025.53000000,39897.00000000,39897.01000000,55.60478100,1627603319999,2220920.05716474,1617,21.86315000,873202.09377572,0,2021-07-30 00:01:59.999000072
2,39897.01000000,40011.11000000,39885.61000000,39979.97000000,55.69423000,1627603379999,2225413.59347086,1465,27.15647700,1085048.87337630,0,2021-07-30 00:02:59.999000072
3,39979.97000000,40050.29000000,39956.25000000,39981.96000000,59.35805400,1627603439999,2374599.79705333,1185,30.98624300,1239439.62536296,0,2021-07-30 00:03:59.999000072
4,39985.07000000,39986.55000000,39919.71000000,39943.93000000,33.51254800,1627603499999,1338703.91030890,898,18.59374000,742750.28823746,0,2021-07-30 00:04:59.999000072
...,...,...,...,...,...,...,...,...,...,...,...,...
12468,43361.38000000,43374.99000000,43343.81000000,43343.81000000,33.66595900,1628351339999,1459671.57933136,1327,15.11799100,655477.26233249,0,2021-08-07 15:48:59.999000072
12469,43343.82000000,43371.88000000,43336.50000000,43336.50000000,42.81003100,1628351399999,1855975.80816632,1019,16.08529700,697370.40028222,0,2021-08-07 15:49:59.999000072
12470,43336.49000000,43423.52000000,43335.37000000,43411.92000000,22.96758400,1628351459999,996491.45306178,965,16.63984100,721925.44461218,0,2021-08-07 15:50:59.999000072
12471,43411.92000000,43440.18000000,43411.92000000,43428.79000000,17.26251000,1628351519999,749666.64323948,663,10.81073100,469466.59950794,0,2021-08-07 15:51:59.999000072
12472,43428.78000000,43443.80000000,43419.29000000,43441.36000000,9.58008400,1628351579999,416024.99000771,205,3.63915900,158055.83149755,0,2021-08-07 15:52:59.999000072

In [85]:
s,e = str(df.date.values[0]).split('T')[0], str(df.date.values[-1]).split('T')[0]
df.to_csv(main_dir+f'/data/{symbol}_{s}_{e}_{interval}.csv')